version: '3.9'

services:
  db_parser:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./image_parser/.env.db
    ports:
      - "5433:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata_parser:/var/lib/postgresql/data
    networks:
      - backend

  db_analyzer:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./image_analyzer/.env.db
    ports:
      - "5434:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata_analyzer:/var/lib/postgresql/data
    networks:
      - backend

  db_job_tracker:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./job_tracker/.env.db
    ports:
      - "5435:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata_job_tracker:/var/lib/postgresql/data
    networks:
      - backend

  image_parser:
    build:
      context: ./image_parser
    env_file:
      - ./image_parser/.env
      - ./image_parser/.env.db
    environment:
      - POSTGRES_SERVER=db_parser
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db_parser
    networks:
      - backend

  image_analyzer:
    build:
      context: ./image_analyzer
    env_file:
      - ./image_analyzer/.env
      - ./image_analyzer/.env.db
    environment:
      - POSTGRES_SERVER=db_analyzer
      - POSTGRES_PORT=5432
    ports:
      - "8001:8001"
    depends_on:
      - db_analyzer
    networks:
      - backend

  job_tracker:
    build:
      context: ./job_tracker
    env_file:
      - ./job_tracker/.env
      - ./job_tracker/.env.db
    environment:
      - POSTGRES_SERVER=db_job_tracker
      - POSTGRES_PORT=5432
    ports:
      - "8002:8002"
    depends_on:
      - db_job_tracker
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env

    environment:
      - VITE_API_URL_IMAGE_PARSER=http://image_parser:8000
      - VITE_API_URL_IMAGE_ANALYZER=http://image_analyzer:8001
      - VITE_API_URL_JOB_TRACKER=http://job_tracker:8002
    ports:
      - "5173:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata_parser:
  pgdata_analyzer:
  pgdata_job_tracker:
  pgdata: