version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: